services:
  postgres:
    image: postgres:17-alpine
    container_name: planfin-db
    restart: unless-stopped
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: planfin
      POSTGRES_PASSWORD: planfin
      POSTGRES_DB: planfin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
